# 开启非传递性 R 类。库的 R 类中将只包含自身声明的资源，不再乱打包依赖进来的下级资源，可极大提升编译速度和减小体积。
android.nonTransitiveRClass=true

# 声明项目全面弃用老旧的 android.support.* 库，全面转接至现代化的 AndroidX 架构体系。
android.useAndroidX=true

# 允许 Gradle Managed Devices (自动化测试管理设备) 在古早 API 级别的老安卓设备/模拟器上运行自动化测试。
android.experimental.testOptions.managedDevices.allowOldApiLevelDevices=true

# 默认关闭所有 Library 模块的 "安卓资源编译" 特性 (res 文件夹如 layout/strings 等)。由于 LSPlant 是纯代码/原生库引擎，关掉它能砍掉巨量没用的打包时间。
android.library.defaults.buildfeatures.androidresources=false

# 强行指定库里的资源 ID (R.id.xx) 保持作为固定常量 (final) 而不是动态变量。这能让传统的 Java switch/case 语句正常用于资源选择符判定。
android.nonFinalResIds=false

# LSPlant: 强制抛弃共享标库，启用全量单体静态包含模式
lsplant.static_stl=true
