plugins {
    alias(libs.plugins.android.library)
    id 'maven-publish'
}

android {
    namespace = "com.asmzx.helper.standalone"

    compileSdk rootProject.ext.androidCompileSdkVersion
    ndkVersion rootProject.ext.androidNdkVersion
    buildToolsVersion rootProject.ext.androidBuildToolsVersion

    buildFeatures {
        prefab true
        prefabPublishing false

        buildConfig false
        androidResources false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    defaultConfig {
        minSdk rootProject.ext.androidMinSdkVersion
        targetSdk rootProject.ext.androidTargetSdkVersion

        externalNativeBuild {
            cmake {
                abiFilters "armeabi-v7a", "arm64-v8a"

                def stlType = project.hasProperty("lsplant.static_stl") ? "c++_static" : "c++_shared"
                arguments(
                        "-DANDROID_STL=${stlType}",
                        "-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON",
                        "-DDEBUG_SYMBOLS_PATH=${project.layout.buildDirectory.file("symbols/standalone").get().asFile.absolutePath}",
                        "-DANDROID_CPP_FEATURES=exceptions;rtti"
                )
            }
        }
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled false
            externalNativeBuild {
                cmake {
                    arguments "-DCMAKE_BUILD_TYPE=Release"
                    cppFlags "-O3"
                    cFlags "-O3"
                }
            }
        }
    }

    externalNativeBuild {
        cmake {
            path = file("CMakeLists.txt")
            version rootProject.ext.androidCmakeVersion
        }
    }

    packagingOptions {
        jniLibs {
            excludes += ["**/libc++_shared.so"]
        }
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
            withJavadocJar()
        }
    }

    lint {
        abortOnError true
        checkReleaseBuilds false
    }
}

dependencies {
    implementation project(':lsplant:build-standalone')
    implementation libs.appcompat
    implementation libs.material
}

task generateStandaloneSymbolsJar(type: Jar) {
    from project.layout.buildDirectory.file("symbols/standalone")
    archiveClassifier = "symbols"
    archiveBaseName = "standalone"
}

def ver = "1.0.0"
println "Helper Standalone version: $ver"

publishing {
    publications {
        helperStandalone(MavenPublication) {
            groupId = "com.asmzx"
            artifactId = "helper-standalone"
            version = ver

            afterEvaluate {
                from components.release
                artifact generateStandaloneSymbolsJar
            }

            pom {
                name = "Helper"
                description = "Helper library for LSPlant - Standalone Package"
                url = "https://github.com/LSPosed/LSPlant"
                licenses {
                    license {
                        name = "GNU Lesser General Public License v3.0"
                        url = "https://github.com/LSPosed/LSPlant/blob/master/LICENSE"
                    }
                }
                developers {
                    developer {
                        name = "asmzx"
                        url = "https://github.com/asmzx"
                    }
                }
                scm {
                    connection = "scm:git:https://github.com/LSPosed/LSPlant.git"
                    url = "https://github.com/LSPosed/LSPlant"
                }
            }
        }
    }
}
